export const randomUserNames = [
  "LuckyPanda92",
  "StarGazer123",
  "CoffeeLover86",
  "SunnySmiles77",
  "AdventureSeeker55",
  "MoonlightDreamer",
  "TechNinja23",
  "HikingHobbyist",
  "Bookworm42",
  "PizzaLover99",
  "GameMasterX",
  "BeachBum22",
  "MusicMaestro77",
  "TravelBug88",
  "NatureExplorer",
  "MovieBuff123",
  "ScienceGeek47",
  "ArtisticSoul",
  "FitnessFanatic",
  "GamerGirlX",
  "WonderWoman1",
  "RockClimber99",
  "DanceDiva45",
  "YogaEnthusiast",
  "FoodieAdventures",
  "SpaceExplorerX",
  "HistoryBuff123",
  "PetLover99",
  "CodingWizard42",
  "CoffeeAddict77",
  "SoccerStar23",
  "MysterySolver55",
  "HikingAdventures",
  "SingingSensation",
  "TechGenius88",
  "MovieCritic123",
  "AnimalWhisperer",
  "PhotographyPro",
  "OutdoorEnthusiast",
  "GamingGuruX",
  "BookNerd47",
  "Traveler123",
  "StarshipCaptain",
  "ArtCollector99",
  "WellnessWarrior",
  "TriviaMasterX",
  "FoodConnoisseur",
  "SkyDiver42",
  "DanceFever77",
  "GardeningGuru",
];

export const randomRoomNames = [
  "Cozy Cabin",
  "Sunny Beachside Retreat",
  "Mystical Enchanted Forest",
  "Starship Explorer",
  "Secret Garden Hideaway",
  "Haunted Mansion",
  "Tropical Paradise Villa",
  "Zen Retreat Oasis",
  "Underwater Wonderland",
  "Mountain Chalet",
  "Galactic Adventure Hub",
  "Whimsical Wonderland",
  "Pirate's Cove",
  "Space Station Alpha",
  "Desert Mirage Lodge",
  "Eco-Friendly Treehouse",
  "Moonlit Meadows Cottage",
  "Atlantis Submarine Base",
  "Time Traveler's Den",
  "Rustic Riverfront Cabin",
  "Steampunk Skyship",
  "Aurora Borealis Lodge",
  "Volcano View Retreat",
  "Hidden Treasure Lair",
  "Jungle Safari Camp",
  "Futuristic Sci-Fi Lab",
  "Medieval Castle Keep",
  "Aloha Beach Bungalow",
  "Lost City Expedition",
  "Wild West Saloon",
  "Eternal Ice Palace",
  "Haunted Pirate Ship",
  "Mountain Peak Sanctuary",
  "Space Odyssey Observatory",
  "Cottage by the Lake",
  "Robotic Factory Workshop",
  "Enchanted Treetop Haven",
  "Underground Bunker",
  "Mermaid Lagoon",
  "Wizard's Tower",
  "Beachfront Paradise",
  "Sky High Penthouse",
  "Ancient Temple Ruins",
  "Hidden Alcove Sanctuary",
  "City Rooftop Garden",
  "Cosmic Voyage Capsule",
  "Alpine Ski Lodge",
  "Subterranean Cavern Hideout",
];
