export const randomUserNames = [
  "LuckyPanda92",
  "StarGazer123",
  "CoffeeLover86",
  "SunnySmiles77",
  "AdventureSeeker55",
  "MoonlightDreamer",
  "TechNinja23",
  "HikingHobbyist",
  "Bookworm42",
  "PizzaLover99",
  "GameMasterX",
  "BeachBum22",
  "MusicMaestro77",
  "TravelBug88",
  "NatureExplorer",
  "MovieBuff123",
  "ScienceGeek47",
  "ArtisticSoul",
  "FitnessFanatic",
  "GamerGirlX",
  "WonderWoman1",
  "RockClimber99",
  "DanceDiva45",
  "YogaEnthusiast",
  "FoodieAdventures",
  "SpaceExplorerX",
  "HistoryBuff123",
  "PetLover99",
  "CodingWizard42",
  "CoffeeAddict77",
  "SoccerStar23",
  "MysterySolver55",
  "HikingAdventures",
  "SingingSensation",
  "TechGenius88",
  "MovieCritic123",
  "AnimalWhisperer",
  "PhotographyPro",
  "OutdoorEnthusiast",
  "GamingGuruX",
  "BookNerd47",
  "Traveler123",
  "StarshipCaptain",
  "ArtCollector99",
  "WellnessWarrior",
  "TriviaMasterX",
  "FoodConnoisseur",
  "SkyDiver42",
  "DanceFever77",
  "GardeningGuru",
];
export const randomRoomNames = [
  "Cozy Corner",
  "Starry Night",
  "Jungle Adventure",
  "Beach Paradise",
  "Secret Garden",
  "Magic Castle",
  "Ocean Breeze",
  "Treasure Hunt",
  "Cosmic Voyage",
  "Mountain Peak",
  "Desert Mirage",
  "Enchanted Forest",
  "Snowy Slopes",
  "Pirate Cove",
  "Hidden Oasis",
  "Moonlit Meadow",
  "Sunny Haven",
  "Crystal Cavern",
  "Mystic Waters",
  "Ancient Ruins",
  "Rainbow Bridge",
  "Whispering Woods",
  "Wild Safari",
  "Moonbeam Bay",
  "Fantasy Realm",
  "Galactic Nexus",
  "Emerald Isle",
  "Serene Sanctuary",
  "Dragon's Lair",
  "Timeless Oasis",
  "Aurora Valley",
  "Lighthouse Cove",
  "Summer Dream",
  "Lost City",
  "Emerald Lagoon",
  "Starship Bridge",
  "Twilight Harbor",
  "Lunar Oasis",
  "Whimsical Woods",
  "Sunflower Meadow",
  "Pirate's Treasure",
  "Mystic Marsh",
  "Eternal Flame",
  "Whispering Winds",
  "Crystal Clear",
  "Enchanted Meadow",
  "Frozen Wonders",
  "Lost World",
  "Cosmic Echoes",
  "Ocean Odyssey",
];
